---
# tasks file for tomcat_setup
#-----CONFIGURE FIREWALL
- name: Start and enable firewall
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Configure firewall for Apache Tomcat
  firewalld:
    port: 8080/tcp
    zone: public
    permanent: yes
    state: enabled
  register: result

- name: Reload firewall
  systemd:
    name: firewalld
    state: reloaded
  when: result.changed
#----------------------------
- name: Installing java-1.8.0-openjdk-devel
  yum:
    name: java-1.8.0-openjdk-devel
    state: latest

- name: Creating tomcat group
  ansible.builtin.group:
    name: tomcat
    state: present

- name: Creating a tomcat user
  user:
    name: tomcat
    password:
    groups: tomcat
    state: present
    shell: /sbin/nologin
    system: no
    createhome: no
    home: /

- name: Downloading and unarchiving tomcat
  ansible.builtin.unarchive:
    src: "https://downloads.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: /opt/
    force: no
    remote_src: yes

- name: Changing tomcat directory owner:group
  ansible.builtin.file:
    path: "/opt/apache-tomcat-{{ tomcat_version }}"
    recurse: yes
    owner: tomcat
    group: tomcat

- name: Creating tomcat.service file
  template:
    src: tomcat.j2
    dest: /etc/systemd/system/tomcat.service

- name: Starting tomcat service
  systemd:
    name: tomcat
    state: started
    daemon_reload: yes
    enabled: yes
